# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
      - release_*
      - test-and-format # just checking if it works - should delete!
  pull_request:
    branches:
      - main
      - release_*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          max-line-length: "88"
          path: "snews_cs"
      - name: Process flake8 output
        if: failure()
        run: |
          flake8_output=$(flake8 snews_cs)
          failing_files=$(echo "$flake8_output" | awk -F: '{print $1}' | sort -u)
          error_message="Linting failed. Please run black on the following files:\n"
          for file in $failing_files; do
            error_message+="black $file\n"
          done
          echo "::error::$error_message"
  # This workflow contains a single job called "build"
  build:
    needs: lint
    strategy:
      matrix:
        # Test all supported Python versions under Ubuntu
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']

    # The type of runner that the job will run on.
    runs-on: ${{ matrix.os }}

    # Tasks executed in the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up the Python environment and dependencies
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install pytest
          python -m pip install poetry
      - name: Install SNEWS_Coincidence_System
        run: |
          python -m poetry install

      - name: Install hop-client
        run: |
          python -m pip install setuptools wheel
          python -m pip install hop-client==0.10.0
          cd /home/runner/work/SNEWS_Coincidence_System/SNEWS_Coincidence_System

      - shell: bash
        env:
          USERNAME: ${{ secrets.hop_user_name }}
          PASSWORD: ${{ secrets.hop_user_password }}
        run: |
          sudo apt-get install -y expect
          which expect
          /usr/bin/expect << HOP
          spawn hop auth add
          expect "Username:"
          send "$USERNAME\n"
          expect "Password:"
          send "$PASSWORD\n"
          expect "Hostname (may be empty):"
          send "kafka.scimma.org\n"
          expect "Token endpoint (empty if not applicable):"
          send "\n"
          expect eof
          HOP
          hop auth locate

      # Run the unit tests
      - name: Test with pytest
        run: |
          python -m poetry run pytest snews_cs
